[[redirects]]
  from = "http://eclipsenetwork.i/*"
  to = "https://eclipsenetwork.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.eclipsenetwork.it/*"
  to = "https://eclipsenetwork.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.eclipsenetwork.i/*"
  to = "https://eclipsenetwork.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
